kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: app-team-project
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
    - namespace: app-team-project*
      server: https://kubernetes.default.svc
      name: in-cluster
  sourceNamespaces:
    - app-team-project
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-team-project
  namespace: app-team-project
spec:
  destination:
    namespace: app-team-project
    server: https://kubernetes.default.svc
  project: app-team-project
  source:
    path: manifests/app-team-project
    repoURL: https://github.com/ophum/kubernetes-practice-lab.git
  syncPolicy:
    automated: {}