apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-guest-book
  namespace: app-team-project
spec:
  destination:
    namespace: app-team-project
    server: https://kubernetes.default.svc
  project: app-team-project
  source:
    path: kustomize-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
  syncPolicy:
    automated: {}