apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    helm.sh/hook: crd-install
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: jetstack/cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.14.3
    helm:
      releaseName: cert-manager
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true