apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.14.3
    helm:
      releaseName: cert-manager
      parameters:
      - name: installCRDs
        value: "true"
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true