apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingres-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.10.0
    helm:
      releaseName: ingress-nginx
      parameters:
      - name: controller.service.loadBalancerIP
        value: 192.168.0.48
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true