apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.6.0
    helm:
      releaseName: longhorn
      valueFiles:
         - values.yaml
      values: |
        persistence:
          defaultClass: false
        preUpgradeChecker:
          jobEnabled: false
        defaultSettings:
          defaultLonghornStaticStorageClass: "longhorn"

