apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingres-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.10.0
    helm:
      releaseName: ingress-nginx
      parameters:
      - name: controller.service.type
        value: ClusterIP
      - name: controller.hostPort.enabled
        value: "true"
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true