apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-sakuracloud
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cert-manager-webhook-sakuracloud
    repoURL: https://ophum.github.io/cert-manager-webhook-sakuracloud
    targetRevision: 0.2.0
    helm:
      releaseName: cert-manager-webhook-sakuracloud
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true