# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  (1..3).each do |id|
    config.vm.define "server#{id}" do |server|
      server.vm.hostname = "server#{id}"
      server.vm.network "private_network", ip: "192.168.56.#{10+id}"

      if id != 1
        server.vm.disk :disk, size: "30GB", name: "vdb"
      end
    end
  end

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4
    vb.memory = "4096"
  end

  config.vm.provision "shell", inline: <<-SHELL
    curl https://github.com/ophum.keys >> /home/vagrant/.ssh/authorized_keys
  SHELL
end