metrics_server_enabled: true

ingress_nginx_enabled: true
ingress_nginx_service_type: LoadBalancer
ingress_nginx_namespace: ingress-nginx
ingress_nginx_class: nginx
ingress_nginx_without_class: true

cert_manager_enabled: true
cert_manager_namesapce: cert-manager

metallb_enabled: true
metallb_protocol: layer2
metallb_config:
  layer2:
  - pool1
  address_pools:
    pool1:
      ip_range:
      - 192.168.0.48/28
      auto_assign: true

argocd_enabled: true
argocd_namespace: argocd

argocd_admin_password: password
