apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.2/manifests/ha/install.yaml
- argocd-server-cluster-apps.yaml
- ./ingress.yaml

patches:
- path: ./argocd-cmd-params-cm.yaml
  target:
    version: v1
    kind: ConfigMap
    name: argocd-cmd-params-cm