---
- name: install pip3
  ansible.builtin.apt:
    name: python3-pip
    state: present
- name: pip3 install kubernetes
  ansible.builtin.pip:
    name: kubernetes

- name: create namespace
  kubernetes.core.k8s:
    name: argocd
    api_version: v1
    kind: Namespace
    state: present
- name: kustomize argocd
  set_fact:
    argocd_resources: "{{ lookup('kubernetes.core.kustomize', dir='../manifests/apps/argocd') }}"

- name: install argocd
  kubernetes.core.k8s:
    definition: "{{ argocd_resources }}"
    
- name: kustomize argocd applications
  set_fact:
    argocd_applications_resources: "{{ lookup('kubernetes.core.kustomize', dir='../manifests/applications') }}"

- name: install argocd applications
  kubernetes.core.k8s:
    definition: "{{ argocd_applications_resources }}"

- name: install sakuracloud-dns-credentials secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: sakuracloud-dns-credentials
        namespace: argocd
      data:
        accessToken: "{{ encrypted_sakuracloud_access_token | string | b64encode }}"
        accessTokenSecret: "{{ encrypted_sakuracloud_access_token_secret | string | b64encode }}"

- name: install issuer    
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: Issuer
      metadata:
        name: letsencrypt-issuer-use-sakuracloud-dns
        namespace: argocd
      spec:
        acme:
          server: https://acme-v02.api.letsencrypt.org/directory
          email: mail@t-inagaki.net
          privateKeySecretRef:
            name: letsencrypt-issuer-use-sakuracloud-dns-issuer-account-key
          solvers:
          - dns01:
              webhook:
                groupName: acme.t-inagaki.net
                solverName: sakuracloud-dns-solver
                config:
                  zoneID: "{{ encrypted_sakuracloud_dns_zone_id }}"
                  accessTokenRef:
                    name: sakuracloud-dns-credentials
                    key: accessToken
                  accessTokenSecretRef:
                    name: sakuracloud-dns-credentials
                    key: accessTokenSecret